version: '3.8'

services:
  # Express.js Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3050:3050"

    networks:
      - app-network
    restart: unless-stopped



nginx-config-backend:
  build:
    context: ./nginx-config
    dockerfile: Dockerfile
  volumes:
    - ./nginx-config/nginx.conf:/nginx.conf:ro
    - /etc/nginx/sites-available:/sites-available
    - /etc/nginx/sites-enabled:/sites-enabled
  command: >
    sh -c "cp -f /nginx.conf /sites-available/flapi.serp24.online &&
           ln -sf /sites-available/flapi.serp24.online /sites-enabled/flapi.serp24.online &&
           ls -l /sites-enabled/flapi.serp24.online &&
           /usr/sbin/nginx -t -c /sites-available/flapi.serp24.online && echo 'NGINX config test passed' || echo 'NGINX config test failed'"
  networks:
    - app-network
    
networks:
  app-network:
    driver: bridge

volumes:
  db-data: